// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_EOF-1]
	_ = x[_Name-2]
	_ = x[_Literal-3]
	_ = x[_Operator-4]
	_ = x[_AssignOp-5]
	_ = x[_IncOp-6]
	_ = x[_Assign-7]
	_ = x[_Define-8]
	_ = x[_Arrow-9]
	_ = x[_Star-10]
	_ = x[_Lparen-11]
	_ = x[_Lbrack-12]
	_ = x[_Lbrace-13]
	_ = x[_Lcaret-14]
	_ = x[_Rparen-15]
	_ = x[_Rbrack-16]
	_ = x[_Rbrace-17]
	_ = x[_Rcaret-18]
	_ = x[_Comma-19]
	_ = x[_Semi-20]
	_ = x[_Colon-21]
	_ = x[_Dot-22]
	_ = x[_DotDotDot-23]
	_ = x[_Pipe-24]
	_ = x[_Break-25]
	_ = x[_Case-26]
	_ = x[_Chan-27]
	_ = x[_Const-28]
	_ = x[_Continue-29]
	_ = x[_Default-30]
	_ = x[_Defer-31]
	_ = x[_Else-32]
	_ = x[_Fallthrough-33]
	_ = x[_For-34]
	_ = x[_Func-35]
	_ = x[_Go-36]
	_ = x[_Goto-37]
	_ = x[_If-38]
	_ = x[_Import-39]
	_ = x[_Interface-40]
	_ = x[_Map-41]
	_ = x[_Package-42]
	_ = x[_Range-43]
	_ = x[_Return-44]
	_ = x[_Select-45]
	_ = x[_Struct-46]
	_ = x[_Switch-47]
	_ = x[_Type-48]
	_ = x[_Var-49]
	_ = x[_Swizzle-50]
	_ = x[_Parse-51]
	_ = x[_Parsel-52]
	_ = x[tokenCount-53]
}

const _token_name = "EOFnameliteralopop=opop=:=<-*([{<)]}>,;:....|breakcasechanconstcontinuedefaultdeferelsefallthroughforfuncgogotoifimportinterfacemappackagerangereturnselectstructswitchtypevarswizzleparseparsel"

var _token_index = [...]uint8{0, 3, 7, 14, 16, 19, 23, 24, 26, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 44, 45, 50, 54, 58, 63, 71, 78, 83, 87, 98, 101, 105, 107, 111, 113, 119, 128, 131, 138, 143, 149, 155, 161, 167, 171, 174, 181, 186, 192, 192}

func (i token) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_token_index)-1 {
		return "token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _token_name[_token_index[idx]:_token_index[idx+1]]
}
